### ISSUE TITLE
Request: Work with Cooking for Blockheads kitchen items

### ISSUE THREAD

**Issue by Lethann** [cpw/inventorysorter#36] opened 2017-02-24 14:02 UTC
Not sure which to post this at so posting at both.

The mod [Cooking for Blockheads](https://github.com/blay09/CookingForBlockheads) has kitchen items like a fridge and counters that have inventory but the sorting feature doesn't work with it.

**Comment by cpw** [comment] 2017-11-26 15:06
Dupe of #39. I need to do an audit of which containers should work and add support for them.

**Closed by cpw** 2017-11-26 15:06 UTC
