### ISSUE TITLE
[1.9] Crash when using mouse scroll wheel anywhere outside inventory

### ISSUE THREAD

**Issue by jesmores** [cpw/inventorysorter#12] opened 2016-03-27 21:57 UTC
[callstack.txt](https://github.com/cpw/inventorysorter/files/191157/callstack.txt)

Above crash log captured when scrolling with inventory open but mouse is not on inventory region.
Also happens in the following UI areas
- Scroll wheel in main menu
- Scroll wheel in World select screen
- Scroll wheel to scroll the keybindings config in options screen

**Comment by tiarnia** [comment] 2016-03-28 02:18
i have same issue even in the inventory window

---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (fastleafdecay-MC1.9-1.2.jar)
  LoadingPlugin (hardcoredarkness-MC1.9-1.8.jar)
  BetterFoliageLoader (betterfoliage-MC1.9-2.0.5.jar)
  LoadingPlugin (bloodmoon-MC1.9-1.4.1.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 3/27/16 8:17 PM
Description: Updating screen events

java.lang.IllegalAccessError: tried to access field net.minecraftforge.client.event.GuiScreenEvent.gui from class cpw.mods.inventorysorter.KeyHandler
	at cpw.mods.inventorysorter.KeyHandler.onKey(KeyHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_KeyHandler_onKey_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:508)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at cpw.mods.inventorysorter.KeyHandler.onKey(KeyHandler.java:40)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_49_KeyHandler_onKey_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:508)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['tiarnia'/281, l='MpServer', x=64.64, y=78.76, z=233.92]]
	Chunk stats: MultiplayerChunkCache: 361, 361
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (80,64,248), Chunk: (at 0,4,8 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1983 game time, 1983 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 90 total; [EntitySkeleton['Skeleton'/128, l='MpServer', x=69.50, y=39.00, z=281.50], EntityZombie['Zombie'/129, l='MpServer', x=73.49, y=22.00, z=292.80], EntitySpider['Spider'/130, l='MpServer', x=68.30, y=24.00, z=292.70], EntityZombie['Zombie'/131, l='MpServer', x=66.50, y=25.00, z=298.50], EntityCreeper['Creeper'/132, l='MpServer', x=76.16, y=21.00, z=296.58], EntityBat['Bat'/133, l='MpServer', x=73.25, y=21.93, z=293.57], EntityChicken['Chicken'/134, l='MpServer', x=70.49, y=112.00, z=312.84], EntityChicken['Chicken'/135, l='MpServer', x=75.50, y=113.00, z=311.50], EntityCreeper['Creeper'/141, l='MpServer', x=99.50, y=15.00, z=166.50], EntityBat['Bat'/142, l='MpServer', x=99.25, y=18.10, z=166.34], EntityZombie['Zombie'/143, l='MpServer', x=107.26, y=18.00, z=223.47], EntitySkeleton['Skeleton'/144, l='MpServer', x=96.50, y=21.00, z=214.50], EntitySpider['Spider'/145, l='MpServer', x=97.50, y=45.00, z=249.50], EntityZombie['Zombie'/146, l='MpServer', x=99.50, y=21.00, z=276.50], EntityPlayerSP['tiarnia'/281, l='MpServer', x=64.64, y=78.76, z=233.92], EntitySquid['Squid'/157, l='MpServer', x=126.37, y=60.82, z=171.60], EntityCreeper['Creeper'/158, l='MpServer', x=124.20, y=19.00, z=235.44], EntityZombie['Zombie'/159, l='MpServer', x=121.50, y=14.00, z=250.50], EntityZombie['Zombie'/160, l='MpServer', x=121.50, y=31.00, z=273.50], EntityCreeper['Creeper'/161, l='MpServer', x=120.50, y=32.00, z=275.50], EntityZombie['Zombie'/33, l='MpServer', x=13.45, y=66.00, z=188.75], EntityZombie['Zombie'/34, l='MpServer', x=14.49, y=13.00, z=234.20], EntityZombie['Zombie'/162, l='MpServer', x=118.53, y=33.00, z=272.81], EntityCreeper['Creeper'/35, l='MpServer', x=1.50, y=23.00, z=260.50], EntitySpider['Spider'/170, l='MpServer', x=143.61, y=16.00, z=219.75], EntitySkeleton['Skeleton'/171, l='MpServer', x=140.50, y=16.00, z=221.50], EntityCreeper['Creeper'/172, l='MpServer', x=143.50, y=32.00, z=219.50], EntitySpider['Spider'/173, l='MpServer', x=134.50, y=42.00, z=212.50], EntitySkeleton['Skeleton'/174, l='MpServer', x=136.43, y=27.00, z=228.21], EntitySkeleton['Skeleton'/175, l='MpServer', x=131.50, y=25.00, z=247.50], EntityBat['Bat'/176, l='MpServer', x=131.67, y=25.10, z=244.52], EntityZombie['Zombie'/177, l='MpServer', x=131.50, y=37.00, z=242.81], EntityCreeper['Creeper'/49, l='MpServer', x=17.48, y=17.00, z=162.17], EntityZombie['Zombie'/50, l='MpServer', x=28.50, y=52.00, z=182.50], EntityCreeper['Creeper'/178, l='MpServer', x=126.56, y=47.00, z=245.64], EntityZombie['Zombie'/51, l='MpServer', x=21.29, y=17.00, z=206.51], EntitySkeleton['Skeleton'/52, l='MpServer', x=18.50, y=43.00, z=213.50], EntityEnderman['Enderman'/180, l='MpServer', x=138.50, y=43.00, z=264.50], EntityZombie['Zombie'/53, l='MpServer', x=26.24, y=43.00, z=213.50], EntityZombie['Zombie'/181, l='MpServer', x=135.52, y=52.00, z=263.24], EntitySkeleton['Skeleton'/54, l='MpServer', x=34.27, y=35.00, z=233.50], EntityBat['Bat'/182, l='MpServer', x=143.48, y=24.10, z=280.48], EntitySquid['Squid'/55, l='MpServer', x=33.60, y=61.00, z=228.65], EntityChicken['Chicken'/183, l='MpServer', x=135.40, y=71.00, z=283.74], EntitySpider['Spider'/56, l='MpServer', x=21.50, y=31.00, z=252.50], EntityChicken['Chicken'/184, l='MpServer', x=141.50, y=66.00, z=285.50], EntityBat['Bat'/57, l='MpServer', x=42.38, y=23.05, z=261.47], EntitySkeleton['Skeleton'/185, l='MpServer', x=142.50, y=26.00, z=291.50], EntityCreeper['Creeper'/58, l='MpServer', x=28.50, y=41.00, z=243.50], EntityChicken['Chicken'/186, l='MpServer', x=142.50, y=67.00, z=293.45], EntityChicken['Chicken'/187, l='MpServer', x=136.45, y=72.00, z=288.83], EntityChicken['Chicken'/60, l='MpServer', x=21.50, y=85.00, z=313.50], EntityCreeper['Creeper'/199, l='MpServer', x=144.50, y=32.00, z=218.50], EntityZombie['Zombie'/74, l='MpServer', x=38.49, y=51.00, z=207.19], EntityCreeper['Creeper'/75, l='MpServer', x=32.50, y=44.00, z=217.50], EntityBat['Bat'/76, l='MpServer', x=38.75, y=25.10, z=233.25], EntityBat['Bat'/77, l='MpServer', x=36.54, y=36.52, z=232.25], EntityZombie['Zombie'/78, l='MpServer', x=47.49, y=22.00, z=241.70], EntityZombie['Zombie'/79, l='MpServer', x=46.25, y=30.00, z=254.17], EntityBat['Bat'/80, l='MpServer', x=41.68, y=20.10, z=257.12], EntityCreeper['Creeper'/81, l='MpServer', x=37.81, y=37.00, z=263.49], EntityCreeper['Creeper'/82, l='MpServer', x=44.50, y=25.00, z=289.50], EntityCreeper['Creeper'/94, l='MpServer', x=52.78, y=41.00, z=172.47], EntitySkeleton['Skeleton'/95, l='MpServer', x=60.66, y=79.00, z=166.72], EntityCreeper['Creeper'/96, l='MpServer', x=48.78, y=35.00, z=201.40], EntityZombie['Zombie'/97, l='MpServer', x=52.52, y=50.00, z=209.20], EntityWitch['Witch'/98, l='MpServer', x=50.50, y=36.00, z=230.50], EntityChicken['Chicken'/99, l='MpServer', x=69.17, y=65.00, z=243.35], EntitySkeleton['Skeleton'/100, l='MpServer', x=53.50, y=44.00, z=247.50], EntityChicken['Chicken'/101, l='MpServer', x=53.51, y=67.00, z=263.16], EntityChicken['Chicken'/102, l='MpServer', x=56.87, y=65.00, z=254.15], EntityChicken['Chicken'/103, l='MpServer', x=49.54, y=69.49, z=246.73], EntityZombie['Zombie'/104, l='MpServer', x=54.50, y=23.00, z=268.50], EntitySkeleton['Skeleton'/105, l='MpServer', x=59.24, y=35.00, z=263.54], EntityChicken['Chicken'/106, l='MpServer', x=63.89, y=111.00, z=307.24], EntityChicken['Chicken'/107, l='MpServer', x=63.82, y=112.00, z=311.47], EntityBat['Bat'/114, l='MpServer', x=69.25, y=40.10, z=174.62], EntityZombie['Zombie'/115, l='MpServer', x=64.46, y=12.00, z=189.74], EntityBat['Bat'/116, l='MpServer', x=72.75, y=23.07, z=183.25], EntitySkeleton['Skeleton'/117, l='MpServer', x=75.24, y=66.00, z=186.50], EntitySheep['Sheep'/118, l='MpServer', x=72.50, y=94.00, z=178.54], EntitySheep['Sheep'/119, l='MpServer', x=72.50, y=94.00, z=177.45], EntitySheep['Sheep'/120, l='MpServer', x=68.48, y=93.00, z=182.82], EntitySheep['Sheep'/121, l='MpServer', x=67.58, y=95.00, z=177.73], EntitySkeleton['Skeleton'/122, l='MpServer', x=72.50, y=15.00, z=203.50], EntitySquid['Squid'/123, l='MpServer', x=68.60, y=61.00, z=204.40], EntityChicken['Chicken'/124, l='MpServer', x=78.43, y=68.17, z=237.49], EntityChicken['Chicken'/125, l='MpServer', x=75.51, y=69.00, z=231.87], EntityChicken['Chicken'/126, l='MpServer', x=77.84, y=69.25, z=245.40], EntityChicken['Chicken'/127, l='MpServer', x=75.47, y=66.00, z=242.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 5746978696 bytes (5480 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms6144m -Xmx6144m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.23 Powered by Forge 12.16.0.1811 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJAAAA	Forge{12.16.0.1811} [Minecraft Forge] (modpack.jar) 
	UCHIJAAAA	cei{1.1} [Chunk Edge Indicator] (1-9-chunkedgeindicator-1.1.jar) 
	UCHIJAAAA	ArmorHud{2.0.1} [ArmorHud] (ArmorHud-1.8.9-2.0.1.jar) 
	UCHIJAAAA	BBG{4.0.0} [BetterBedrockGen] (betterbedrockgenerator-1.9.0-3.0.0.jar) 
	UCHIJAAAA	BetterFoliage{2.0.5} [Better Foliage] (betterfoliage-MC1.9-2.0.5.jar) 
	UCHIJAAAA	JEI{3.1.0.170} [Just Enough Items] (jei-1.9-3.1.0.170.jar) 
	UCHIJAAAA	BloodMagic{1.9-2.0.0-25} [Blood Magic: Alchemical Wizardry] (bloodmagic-1.9-2.0.0-25.jar) 
	UCHIJAAAA	Bloodmoon{1.2} [Bloodmoon] (bloodmoon-MC1.9-1.4.1.jar) 
	UCHIJAAAA	Chameleon{1.9-2.1.0} [Chameleon] (chameleon-1.9-2.1.0.jar) 
	UCHIJAAAA	FastLeaveDecay{1.1} [Fast Leave Decay] (fastleafdecay-MC1.9-1.2.jar) 
	UCHIJAAAA	HardcoreDarkness{1.8} [Hardcore Darkness] (hardcoredarkness-MC1.9-1.8.jar) 
	UCHIJAAAA	inventorysorter{0.7.8+28} [Simple Inventory sorting] (inventorysorter-1.9-0.7.8+28.jar) 
	UCHIJAAAA	ModNameTooltip{1.2.0} [Mod Name Tooltip] (modnametooltip_1.9-1.2.0.jar) 
	UCHIJAAAA	Neat{GRADLE:VERSION-GRADLE:BUILD} [Neat] (Neat 1.2-5.jar) 
	UCHIJAAAA	substratum{1.2.0.0} [Substratum] (substratum-1.9-1.2.0.0.jar) 
	UCHIJAAAA	WIT{1.0.9} [WIT] (wit-1.9-1.0.9-23.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (fastleafdecay-MC1.9-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
LoadingPlugin (hardcoredarkness-MC1.9-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
BetterFoliageLoader (betterfoliage-MC1.9-2.0.5.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
LoadingPlugin (bloodmoon-MC1.9-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.1001' Renderer: 'AMD Radeon (TM) R9 390 Series'
	Launched Version: 1.9-forge1.9-12.16.0.1811-1.9
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R9 390 Series GL version 4.5.13416 Compatibility Profile Context 15.300.1025.1001, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4460 CPU @ 3.20GHz

**Comment by LlubNek** [comment] 2016-03-29 07:29
Same here.  Mousewheel in key config screen.
http://pastebin.com/vkbMF7RM

**Comment by jesmores** [comment] 2016-03-29 16:20
#13 might fix this, but I haven't figured out how to setup a 1.9 build env to confirm

**Comment by 4rz0** [comment] 2016-04-07 19:22
Same issue, inside key ocnfig screen.

**Comment by tiarnia** [comment] 2016-04-12 05:08
kicks me off server is i mouse click in 1.9 right now so at the moment this mod does nothing

**Comment by cpw** [comment] 2016-04-21 02:36
Closing, duplicate of #13

**Closed by cpw** 2016-04-21 02:36 UTC
