### ISSUE TITLE
[Suggestion] More sorting rules please!

### ISSUE THREAD

**Issue by Arrowpuppet** [cpw/inventorysorter#101] opened 2020-11-04 00:01 UTC
The default sorting rules are very confusing and don't seem like they actually 'sort' inventories at all. I'd love to see an option in config to switch the the creative menu sorting rule that inventory tweaks implements, so inventories actually feel like they are sorted. Looking forward to this being added in future versions!

**Comment by Jables2121** [comment] 2020-11-24 03:19
I second this 1000% there is no reason to sort by stack size. That changes constantly. You said 3 years ago that you were looking in to adding alphabetical sorting. It amazes me that mod packs like Valhelsia include this without it having any useful sorting options.

**Comment by JakeMoe** [comment] 2021-11-21 08:29
This appears to be a duplicate of #37

**Closed** 2022-01-16 14:42 UTC
