### ISSUE TITLE
SimpleChannelHandlerWrapper exception

### ISSUE THREAD

**Issue by Sasikaa** [cpw/inventorysorter#5] opened 2016-01-22 09:11 UTC
When middle click the inventory (doublechest) inside the chest enchanted items (books, and items)
crashing, and NOT crash report. This is my LOG file paste!!!

http://pastebin.com/p63mveMs

**Comment by Sasikaa** [comment] 2016-01-22 21:06
Hm? Any update soon this bug or issue solved?

**Comment by cpw** [comment] 2016-03-19 23:03
Duplicate of #1

**Closed by cpw** 2016-03-19 23:03 UTC
